name: interoperability
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::jupyterlab==3.6.1
  - conda-forge::scanpy=1.9.1
  - anndata==0.8.0
  - anndata2ri==1.1
  - bioconductor-basilisk==1.9.12
  - bioconductor-singlecellexperiment==1.20.0
  - bioconductor-zellkonverter==1.8.0
  - igraph==0.10.3
  - matplotlib<3.7
  - numpy==1.23.5
  - pip==23.0
  - python-igraph=0.10.4
  - conda-forge::r-base=4.2.2
  - r-reticulate=1.26
  - r-sessioninfo=1.2.2
  - r-seurat=4.3.0
  - rpy2=3.5.8
  - scipy=1.10.0
  - session-info=1.0.0
