name: Build environments

on: [push, pull_request]

jobs:
  Build-environments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        s:
          [
            "jupyter-book/introduction/analysis_tools.yml",
            "jupyter-book/preprocessing_visualization/preprocessing.yml",
            "jupyter-book/cellular_structure/clustering.yml",
            "jupyter-book/cellular_structure/annotation.yml",
            "jupyter-book/cellular_structure/integration.yml",
            "jupyter-book/conditions/compositional.yml",
          ]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          channel-priority: disabled
          cache-downloads: true
          environment-file: ${{ matrix.environments }}
          environment-name: currentenv
